name = "prototype-hono-drizzle-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "prototype-hono-drizzle-db"
database_id = "59d1bb59-6480-433f-9f7d-3f24330873cc" # To be filled when creating the D1 database

# For local development
[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "prototype-hono-drizzle-db-dev"
database_id = "" # Local D1 database ID

# For production
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "prototype-hono-drizzle-db-prod"
database_id = "" # Production D1 database ID
